[theme]
base = "light"
primaryColor = "#3c25ec"
backgroundColor = "#f4f5fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#09073e"
font = "sans serif"

[server]
port = 8000
headless = true
enableCORS = false
enableXsrfProtection = false
